# Generated by Django 5.2.17 on 2026-09-20 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_chore_chorecompletion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningMutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(unique=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_mutations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedDinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_dinners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dinnerplan',
            name='saved_dinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='planning.saveddinner'),
        ),
        migrations.CreateModel(
            name='DinnerPlanIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('normalized_name', models.CharField(db_index=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(choices=[('produce', 'Produce'), ('meat', 'Meat'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('pantry', 'Pantry'), ('frozen', 'Frozen'), ('drinks', 'Drinks'), ('household', 'Household'), ('toiletries', 'Toiletries'), ('other', 'Other')], default='other', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='planning.dinnerplan')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 999)), name='dinner_plan_ingredient_quantity_range')],
            },
        ),
        migrations.CreateModel(
            name='SavedDinnerIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('normalized_name', models.CharField(db_index=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(choices=[('produce', 'Produce'), ('meat', 'Meat'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('pantry', 'Pantry'), ('frozen', 'Frozen'), ('drinks', 'Drinks'), ('household', 'Household'), ('toiletries', 'Toiletries'), ('other', 'Other')], default='other', max_length=20)),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='planning.saveddinner')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 999)), name='saved_dinner_ingredient_quantity_range')],
            },
        ),
    ]
