# Generated by Django 5.2.17 on 2026-09-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='household',
            name='weather_latitude',
            field=models.DecimalField(decimal_places=5, default=-36.84846, max_digits=8),
        ),
        migrations.AddField(
            model_name='household',
            name='weather_location',
            field=models.CharField(default='Auckland', max_length=100),
        ),
        migrations.AddField(
            model_name='household',
            name='weather_longitude',
            field=models.DecimalField(decimal_places=5, default=174.76334, max_digits=8),
        ),
    ]
