# Generated by Django 5.2.17 on 2026-09-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0002_weathersnapshot_household_weather_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='weather_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
