# Generated by Django 5.2.17 on 2026-09-19 13:37

import household.appearance
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0003_household_weather_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='appearance_preset',
            field=models.CharField(choices=[('classic', 'Classic'), ('minimal', 'Minimal'), ('warm', 'Warm'), ('contrast', 'Contrast'), ('modern', 'Modern')], default='classic', max_length=24),
        ),
        migrations.AddField(
            model_name='household',
            name='appearance_values',
            field=models.JSONField(default=household.appearance.classic_defaults),
        ),
    ]
