# Generated by Django 5.2.17 on 2026-09-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0005_household_base_preset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='base_preset',
            field=models.CharField(choices=[('classic', 'Classic'), ('minimal', 'Minimal'), ('soft', 'Soft'), ('editorial', 'Editorial'), ('dense', 'Dashboard')], default='classic', max_length=24),
        ),
    ]
