# Generated by Django 5.2.17 on 2026-09-15 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(unique=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('normalized_name', models.CharField(db_index=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('purchased', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_items', to=settings.AUTH_USER_MODEL)),
                ('purchased_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchased_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 999)), name='shopping_quantity_range')],
            },
        ),
    ]
