# Generated by Django 5.2.17 on 2026-09-20 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_planningmutation_saveddinner_dinnerplan_saved_dinner_and_more'),
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('canonical_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('produce', 'Produce'), ('meat', 'Meat'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('pantry', 'Pantry'), ('frozen', 'Frozen'), ('drinks', 'Drinks'), ('household', 'Household'), ('toiletries', 'Toiletries'), ('other', 'Other')], default='other', max_length=20)),
                ('uses', models.PositiveIntegerField(default=1)),
                ('spellings', models.JSONField(default=dict)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='category',
            field=models.CharField(choices=[('produce', 'Produce'), ('meat', 'Meat'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('pantry', 'Pantry'), ('frozen', 'Frozen'), ('drinks', 'Drinks'), ('household', 'Household'), ('toiletries', 'Toiletries'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='dinner_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_items', to='planning.dinnerplan'),
        ),
    ]
