# Generated by Django 5.2.17 on 2026-09-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_knownitem_shoppingitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownitem',
            name='category',
            field=models.CharField(blank=True, choices=[('produce', 'Produce'), ('meat', 'Meat'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('pantry', 'Pantry'), ('frozen', 'Frozen'), ('drinks', 'Drinks'), ('household', 'Household'), ('toiletries', 'Toiletries'), ('other', 'Other')], default=None, max_length=20, null=True),
        ),
    ]
